.TH "PAKT" "1" "September 2024" "pakt v0.0.1" "User Commands"

.SH NAME
pakt-sync \- perform relevant pakt category actions

.SH SYNOPSIS
\fIpakt-sync\fR category
.LP
\fIpakt-sync\fR -f path

.SH DESCRIPTION
TODO DESCRIPTION

.SH OPTIONS
TODO OPTIONS

.SH ENVIRONMENT
TODO ENVIRONMENT

.SH FILES
TODO FILES

.SH AUTHORS
\" TODO ASK name
Sergey Lavrent <https://github.com/hiimsergey>
.LP
MrMineDe <https://github.com/mrminede>

.SH LICENSE
GPLv2: GNU General Public License version 2
.LP
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by the law.

.SH BUGS
https://github.com/mrminede/pakt/issues
