.TH "PAKT" "1" "October 2024" "pakt v0.1.0" "User Commands"

.SH NAME
pakt-dry \- perform relevant pakt category actions

.SH SYNOPSIS
\fIpakt-dry\fR (category|path) ...
.LP
\fIpakt-dry \fB-S\fR (package ... category ...) ...
.LP
\fIpakt-dry \fB-R\fR (package ... category ...) ...

.SH DESCRIPTION
pakt-dry is a pakt suite script responsible for querying and manipulating category files without performing actual pacman transactions.

You can either query category files by using the same plus character syntax as in pakt or giving a file path. In the latter case, it's essentially a cat action.

To look up the category syntax, see \fBpakt\fR(1).

.SH OPTIONS
\fB-h\fR, \fB--help\fR
.br
       Shows this man page.

\fB-S\fR, \fB--sync\fR
.br
       Performs the same category assignment as when installing packages with pakt
.br
       but no packages will be installed.

\fB-R\fR, \fB--remove\fR
.br
       Performs the same category deletion as when uninstalling packages with pakt
.br
       but no packages will be uninstalled.

No arguments at all will take you to this man page, if the \fBman\fR command is available.

.SH EXAMPLES
\fIpakt-dry\fR +core,cli
.br
       Prints out the contents of the files \fIcore\fR and \fIcli\fR in the category directory,
.br
       so either \fI~/.local/share/pakt/\fR or \fI$XDG_DATA_HOME/pakt/\fR, if \fI$XDG_DATA_HOME\fR is set.

\fIpakt-dry\fR +core,cli ~/Documents/arch_stuff.txt
.br
       Besides the former action, also prints out the contents of \fI~/Documents/arch_stuff.txt\fR.

\fIpakt-dry\fR -S neovim +core,cli,dev
.br
       Assigns neovim to the categories \fBcore\fR, \fBcli\fR and \fBdev\fR, regardless whether
.br
       neovim is actually installed.

\fIpakt-dry\fR -R neovim +dev
.br
       Removes neovim from category \fBdev\fR only but keeps neovim on the system, if
.br
       it was installed before.

.SH ENVIRONMENT
PAKT_CONF_PATH
.br
       Path of the \fIpakt.conf\fR configuration file. Defaults to \fI/etc\fR.

.SH FILES
\fI/etc/pakt.conf\fR
.br
       Default address of the configuration file. Look into the file for more information.

\fI/etc/pakt.conf.default\fR
.br
       Default configuration options for \fIpakt.conf\fR.
.br
       It's also a part of the souce code at \fIpakt.conf.default\fR.

\fI~/.local/share/pakt/\fR
.br
       Path containing category files, if \fI$XDG_DATA_HOME\fR is not set.
.br
       Category files are plain lists of packages assigned to the respective category.

.SH AUTHORS
Sergey Lavrent <https://github.com/hiimsergey>
.LP
MrMineDe <https://github.com/mrminede>

.SH LICENSE
GPLv2: GNU General Public License version 2
.LP
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by the law.

.SH BUGS
https://github.com/mrminede/pakt/issues

.SH SEE ALSO
\fBpakt\fR(1) \fBpakt-sync\fR(1)
