.TH "PAKT" "1" "September 2024" "pakt v0.0.1" "User Commands"

.SH NAME
pakt-sync \- perform transactions from entire category files

.SH SYNOPSIS
\fIpakt-sync [(package|category) ...]
.LP
\fIpakt-sync\fR \fB-S\fR (category|path) ...
.LP
\fIpakt-sync \fB-R\fR (package|category) ...

.SH DESCRIPTION
pakt-sync is a pakt suite script responsible for installing packages from list files, including your category files. Thus, it fulfills a core purpose for categories, trying to kind of emulate NixOS' functionality.

You can either pass files by using the same plus character syntax as in pakt or giving a file path.

To look up the category syntax, see \fBpakt\fR(1).

.SH OPTIONS
\fB<none>\fR
.br
       Shows not installed packages from the line-by-line lists in the given +categories
.br
       or file paths.

\fB-h\fR, \fB--help\fR
.br
       Shows this man page.

\fB-S\fR, \fB--sync\fR
.br
       Installs all packages listed line-by-line in the given +categories or file paths.

\fB-R\fR, \fB--remove\fR
.br
       Removes all packages listed line-by-line in the given +categories or file paths.

No arguments at all will take you to this man page, if the \fBman\fR command is available.

.SH EXAMPLES
\fIpakt-sync\fR +cli ~/Documents/pacman_Qe_090124.txt
.br
       Lists all not installed packages both from the \fBcli\fR category and the
.br
       \fI~/Documents/pacman_Qe_090124.txt\fR file.

\fIpakt-sync\fR -S +dev
.br
       Installs all packages listed in the \fBdev\fR category file.

\fIpakt-sync\fR -R ~/Downloads/xorg-packages.txt
.br
       Removes all packages listed line-by-line in the \fI~/Downloads/xorg-packages.txt\fR file.

.SH ENVIRONMENT
PAKT_CONF_PATH
.br
       Path of the \fIpakt.conf\fR configuration file. Defaults to \fI/etc\fR.

.SH FILES
\fI/etc/pakt.conf\fR
.br
       Default address of the configuration file. Look into the file for more information.

\fI/etc/pakt.conf.default\fR
.br
       Default configuration options for \fIpakt.conf\fR.
.br
       It's also a part of the souce code at \fIpakt.conf.default\fR.

\fI~/.local/share/pakt/\fR
.br
       Path containing category files, if $XDG_DATA_HOME is not set.
.br
       Category files are plain lists of packages assigned to the respective category.

.SH AUTHORS
Sergey Lavrent <https://github.com/hiimsergey>
.LP
MrMineDe <https://github.com/mrminede>

.SH LICENSE
GPLv2: GNU General Public License version 2
.LP
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by the law.

.SH BUGS
https://github.com/mrminede/pakt/issues

.SH SEE ALSO
\fBpakt\fR(1) \fBpakt-sync\fR(1)
